Comenzamos cargando el dataset para este ejercicio: usaremos el dataset disponible en el repositorio de GitHub: **50-startups**

Este dataset también está disponible en la plataforma Kaggle.
Link: [Dataset](https://www.kaggle.com/farhanmd29/50-startups)

In [2]:
url = "https://raw.githubusercontent.com/gakudo-ai/open-datasets/refs/heads/main/50_Startups.csv"

Cargamos el dataset en un DataFrame de Pandas, y echamos un vistazo a las primeras 5 instancias.

In [3]:
import pandas as pd

df = pd.read_csv(url)
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

La variable objetivo a predecir (etiqueta) es **Profit** (rentabilidad de la Startup) y existen cuatro atributos predictores: tres de ellos numéricos y el cuarto es categórico (**State**). En este ejemplo omitiremos la información contenida en el atributo categórico, limitándonos únicamente a usar los tres numéricos.

In [4]:
df_num = df.drop('State', axis=1) # Eliminar atributo categórico
df_num.head()

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

Separar atributos predictores (X) de la etiqueta (y), y particionar el dataset en conjuntos de **entrenamiento** (80%) y **test** (20%).

El método *train_test_split()* de scikit-learn nos ayuda a hacer este particionado de forma aleatoria, mediante muestreo. Usar el argumento *random_state* es opcional, pero ayuda a que nuestro código sea reproducible.

In [5]:
X = df_num.drop('Profit',axis=1)
y = df_num['Profit']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

Entrenaremos un modelo de regresión lineal múltiple usando la clase using **LinearRegression** de *scikit-learn*, tras lo cual realizaremos predicciones sobre el conjunto de ejemplos de test.

In [6]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train) # Se usan tanto los atributos X como las etiquetas y para entrenar el modelo

y_predictions =  lin_reg.predict(x_test)
y_predictions

array([126703.02716461,  84894.75081556,  98893.41815974,  46501.70815036,
       129128.39734381,  50992.69486261, 109016.5536578 , 100878.4641454 ,
        97700.59638629, 113106.15292226])

Calcular el **error** (RMSE, root mean squared error) cometido en las predicciones hechas por el modelo:

In [7]:
from sklearn.metrics import mean_squared_error
import numpy as np

# CUIDADO: la raíz cuadrada no la aplica la función que usaremos. Tendremos que calcularla manualmente
lin_mse = mean_squared_error(y_test, y_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

np.float64(8995.905803361415)

In [13]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predictions)
print(f"Coeficiente de determinación R2: {r2}")

Coeficiente de determinación R2: 0.9000653083037321

**EJERCICIOS PROPUESTOS**



1.   Mediante las modificaciones u operaciones pertinentes sobre el *dataset*, y entrenando nuevos modelos, averiguar si un solo atributo aislando o bien un subconjunto de dos atributos cualesquiera, podría ser un buen predictor de la rentabilidad o **Profit** de una startup. Para ello, necesitarás construir varios modelos de regresión lineal adicionales, que no tengan en cuenta todos los atributos numéricos, sino solo uno o dos de ellos.
2.   Analizar si alguno de los modelos entrenados sufre del problema de sobreajuste (**overfitting**): el modelo hace muy buenas predicciones sobre los propios ejemplos usados para el entrenamiento, pero funciona bastante peor sobre los ejemplos de test.

In [9]:
x_train_new = x_train[["Administration", "Marketing Spend"]]
x_test_new = x_test[["Administration", "Marketing Spend"]]

In [10]:
lin_reg_new = LinearRegression()
lin_reg_new.fit(x_train_new,y_train) # Usar datos de entrenamiento + etiquetas para aprender y construir el modelo de regresión

y_predictions_new =  lin_reg_new.predict(x_test_new)

In [11]:
lin_mse_new = mean_squared_error(y_test, y_predictions_new)
lin_rmse_new = np.sqrt(lin_mse_new)
lin_rmse_new

np.float64(27199.55823065952)

In [12]:
y_predictions_train = lin_reg.predict(x_train)
lin_mse_train = mean_squared_error(y_train, y_predictions_train)
lin_rmse_train = np.sqrt(lin_mse_train)

print(f"RMSE sobre datos de entrenamiento: {lin_rmse_train}")
print(f"RMSE sobre datos de test: {lin_rmse}")

if lin_rmse_train < lin_rmse*0.95: # Umbral establecido por nosotros: error de entrenamiento menor que 0.95*test
    print("\nEl modelo se comporta visiblemente mejor en datos de entrenamiento que de test: posible overfitting.")
else:
    print("\nEl comportamiento del modelo es similar entre datos de entrenamiento y test.")

RMSE sobre datos de entrenamiento: 8938.013440232062
RMSE sobre datos de test: 8995.905803361415

El comportamiento del modelo es similar entre datos de entrenamiento y test.